name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      options:
        - LogNorth
        - Fusionaly
        - Pomotto
        - Formlander
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell me what went wrong.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: What should have happened instead.
    validations:
      required: false
